# Generated by Django 4.2.10 on 2024-03-25 11:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Имя")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                ("exp", models.IntegerField(default=0, verbose_name="Опыт")),
                (
                    "exp_for_level_up",
                    models.IntegerField(
                        default=500, verbose_name="Опыт для достижения уровня"
                    ),
                ),
                ("attack", models.IntegerField(default=0, verbose_name="Атака")),
                ("defence", models.IntegerField(default=0, verbose_name="Защита")),
                (
                    "exp_modifier",
                    models.IntegerField(default=1, verbose_name="Модмфикатор опыта"),
                ),
                (
                    "drop_modifier",
                    models.IntegerField(default=1, verbose_name="Модификатор дропа"),
                ),
                (
                    "premium_expired",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Окончание Премиума",
                    ),
                ),
                (
                    "hunting_begin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало охоты"
                    ),
                ),
                (
                    "hunting_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Конец охоты"
                    ),
                ),
                (
                    "max_hunting_time",
                    models.TimeField(
                        default=datetime.time(4, 0),
                        verbose_name="Максимальное время охоты",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="ID шедулера напоминания об окончании охоты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
            },
        ),
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Имя")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "emoji",
                    models.CharField(max_length=8, null=True, verbose_name="Эмоджи"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("attack", models.IntegerField(default=0, verbose_name="Атака")),
                ("defence", models.IntegerField(default=0, verbose_name="Защита")),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
            },
        ),
        migrations.CreateModel(
            name="CharacterClassSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение класса",
                "verbose_name_plural": "Умения классов",
            },
        ),
        migrations.CreateModel(
            name="CharacterEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expired",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Окончание Эффекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эффект персонажа",
                "verbose_name_plural": "Эффекты персонажа",
            },
        ),
        migrations.CreateModel(
            name="CharacterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=1, verbose_name="Количество")),
                ("equipped", models.BooleanField(default=False, verbose_name="Надето")),
                (
                    "enhancement_level",
                    models.IntegerField(default=0, verbose_name="Уровень улучшения"),
                ),
            ],
            options={
                "verbose_name": "Предмет персонажа",
                "verbose_name_plural": "Предметы персонажа",
            },
        ),
        migrations.CreateModel(
            name="CharacterRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт персонажа",
                "verbose_name_plural": "Рецепты персонажа",
            },
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение персонажа",
                "verbose_name_plural": "Умения персонажей",
            },
        ),
        migrations.CreateModel(
            name="ClassEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("heavy_armor", "Тяжелая Броня"),
                            ("light_armor", "Легкая Броня"),
                            ("robe", "Мантия"),
                            ("sword", "Меч"),
                            ("staff", "Посох"),
                            ("blunt", "Дубина"),
                            ("dagger", "Кинжал"),
                            ("bracelet", "Браслет"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Вид экипировки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Классовая экипировка",
                "verbose_name_plural": "Классовые экипировки",
            },
        ),
        migrations.CreateModel(
            name="MarketplaceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "enhancement_level",
                    models.IntegerField(default=0, verbose_name="Уровень улучшения"),
                ),
                ("price", models.IntegerField(default=1, verbose_name="Стоимость")),
            ],
            options={
                "verbose_name": "Предмет на Торговой Площадке",
                "verbose_name_plural": "Предметы на Торговой Площадке",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
            ],
            options={
                "verbose_name": "Умение",
                "verbose_name_plural": "Умения",
            },
        ),
        migrations.CreateModel(
            name="SkillEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эффект способности",
                "verbose_name_plural": "Эффекты способностей",
            },
        ),
    ]
