# Generated by Django 4.2.10 on 2024-04-18 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Имя")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                ("exp", models.IntegerField(default=0, verbose_name="Опыт")),
                (
                    "exp_for_level_up",
                    models.IntegerField(
                        default=500, verbose_name="Опыт для достижения уровня"
                    ),
                ),
                ("attack", models.IntegerField(default=10, verbose_name="Атака")),
                ("defence", models.IntegerField(default=10, verbose_name="Защита")),
                (
                    "crit_rate",
                    models.IntegerField(default=50, verbose_name="Шанс Крита"),
                ),
                (
                    "crit_power",
                    models.IntegerField(default=50, verbose_name="Сила Крита"),
                ),
                ("evasion", models.IntegerField(default=10, verbose_name="Уклонение")),
                ("accuracy", models.IntegerField(default=10, verbose_name="Точность")),
                ("health", models.IntegerField(default=24, verbose_name="Здоровье")),
                (
                    "max_health",
                    models.IntegerField(default=24, verbose_name="Макс здоровье"),
                ),
                ("mana", models.IntegerField(default=16, verbose_name="Мана")),
                ("max_mana", models.IntegerField(default=16, verbose_name="Макс мана")),
                (
                    "skill_points",
                    models.IntegerField(default=0, verbose_name="Очки Характеристик"),
                ),
                (
                    "premium_expired",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Окончание Премиума",
                    ),
                ),
                (
                    "hunting_begin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало охоты"
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="ID шедулера напоминания об окончании охоты",
                    ),
                ),
                ("kills", models.IntegerField(default=0, verbose_name="Убийств")),
                (
                    "auto_use_hp_potion",
                    models.BooleanField(
                        default=False,
                        verbose_name="Автоиспользование эликсиров здоровья",
                    ),
                ),
                (
                    "auto_use_mp_potion",
                    models.BooleanField(
                        default=False, verbose_name="Автоиспользование эликсиров маны"
                    ),
                ),
                (
                    "pvp_mode_expired",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Окончание PvP режима",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
            },
        ),
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Имя")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "emoji",
                    models.CharField(max_length=8, null=True, verbose_name="Эмоджи"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("attack", models.IntegerField(default=0, verbose_name="Атака")),
                ("defence", models.IntegerField(default=0, verbose_name="Защита")),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
            },
        ),
        migrations.CreateModel(
            name="CharacterClassSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение класса",
                "verbose_name_plural": "Умения классов",
            },
        ),
        migrations.CreateModel(
            name="CharacterEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expired",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Окончание Эффекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эффект персонажа",
                "verbose_name_plural": "Эффекты персонажа",
            },
        ),
        migrations.CreateModel(
            name="CharacterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                ("equipped", models.BooleanField(default=False, verbose_name="Надето")),
                (
                    "enhancement_level",
                    models.IntegerField(default=0, verbose_name="Уровень улучшения"),
                ),
            ],
            options={
                "verbose_name": "Предмет персонажа",
                "verbose_name_plural": "Предметы персонажа",
            },
        ),
        migrations.CreateModel(
            name="CharacterPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сила персонажа",
                "verbose_name_plural": "Силы персонажей",
            },
        ),
        migrations.CreateModel(
            name="CharacterRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт персонажа",
                "verbose_name_plural": "Рецепты персонажа",
            },
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turn_on",
                    models.BooleanField(
                        default=False, verbose_name="Активирован (Для переключаемых)"
                    ),
                ),
                (
                    "cooldown",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Перезарядкаа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение персонажа",
                "verbose_name_plural": "Умения персонажей",
            },
        ),
        migrations.CreateModel(
            name="ClassEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("heavy_armor", "Тяжелая Броня"),
                            ("light_armor", "Легкая Броня"),
                            ("robe", "Мантия"),
                            ("sword", "Меч"),
                            ("staff", "Посох"),
                            ("blunt", "Дубина"),
                            ("dagger", "Кинжал"),
                            ("bracelet", "Браслет"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Вид экипировки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Классовая экипировка",
                "verbose_name_plural": "Классовые экипировки",
            },
        ),
        migrations.CreateModel(
            name="MarketplaceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "enhancement_level",
                    models.IntegerField(default=0, verbose_name="Уровень улучшения"),
                ),
                ("price", models.IntegerField(default=1, verbose_name="Стоимость")),
            ],
            options={
                "verbose_name": "Предмет на Торговой Площадке",
                "verbose_name_plural": "Предметы на Торговой Площадке",
            },
        ),
        migrations.CreateModel(
            name="Power",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Сила",
                "verbose_name_plural": "Силы",
            },
        ),
        migrations.CreateModel(
            name="RecipeShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Рецепт на Торговой Площадке",
                "verbose_name_plural": "Рецпты на Торговой Площадке",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                (
                    "emoji",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Эмоджи"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                ("mana_cost", models.IntegerField(default=0, verbose_name="Мана кост")),
                (
                    "effect_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время действия"
                    ),
                ),
                (
                    "cooldown",
                    models.TimeField(blank=True, null=True, verbose_name="Перезарядка"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("passive", "Пассивная"),
                            ("toggle", "Переключаемая"),
                            ("active", "Активная"),
                        ],
                        default="passive",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение",
                "verbose_name_plural": "Умения",
            },
        ),
        migrations.CreateModel(
            name="SkillEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эффект способности",
                "verbose_name_plural": "Эффекты способностей",
            },
        ),
    ]
