# Generated by Django 4.2.10 on 2024-02-22 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item", "0001_initial"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseCharacterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Имя")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "basecharactermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="character.basecharactermodel",
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                ("exp", models.IntegerField(default=0, verbose_name="Опыт")),
                (
                    "exp_for_level_up",
                    models.IntegerField(
                        default=100, verbose_name="Опыт для достижения уровня"
                    ),
                ),
                ("attack", models.IntegerField(default=0, verbose_name="Атака")),
                ("defence", models.IntegerField(default=0, verbose_name="Защита")),
                (
                    "hunting_begin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало охоты"
                    ),
                ),
                (
                    "hunting_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Конец охоты"
                    ),
                ),
                (
                    "max_hunting_time",
                    models.TimeField(
                        default=datetime.time(4, 0),
                        verbose_name="Максимальное время охоты",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="ID шедулера напоминания об окончании охоты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
            },
            bases=("character.basecharactermodel",),
        ),
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "basecharactermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="character.basecharactermodel",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=256, verbose_name="Описание"),
                ),
                ("attack", models.IntegerField(default=0, verbose_name="Атака")),
                ("defence", models.IntegerField(default=0, verbose_name="Защита")),
                (
                    "attack_level_increase",
                    models.IntegerField(
                        default=1, verbose_name="Прирост атаки за уровень"
                    ),
                ),
                (
                    "defence_level_increase",
                    models.IntegerField(
                        default=1, verbose_name="Прирост защиты за уровень"
                    ),
                ),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
            },
            bases=("character.basecharactermodel",),
        ),
        migrations.CreateModel(
            name="CharacterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет персонажа",
                "verbose_name_plural": "Предметы персонажа",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="character_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="character.characterclass",
                verbose_name="Класс персонажа",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="current_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="location.location",
                verbose_name="Текущая локация",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="items",
            field=models.ManyToManyField(
                related_name="items", through="character.CharacterItem", to="item.item"
            ),
        ),
    ]
