# Generated by Django 4.2.10 on 2024-03-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_bag_equipment_potion_remove_armor_armor_type_and_more"),
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
            ],
            options={
                "verbose_name": "Умение",
                "verbose_name_plural": "Умения",
            },
        ),
        migrations.RemoveField(
            model_name="characterclass",
            name="attack_level_increase",
        ),
        migrations.RemoveField(
            model_name="characterclass",
            name="defence_level_increase",
        ),
        migrations.AddField(
            model_name="character",
            name="drop_modifier",
            field=models.IntegerField(default=1, verbose_name="Модификатор дропа"),
        ),
        migrations.AddField(
            model_name="character",
            name="exp_modifier",
            field=models.IntegerField(default=1, verbose_name="Модмфикатор опыта"),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="emoji",
            field=models.CharField(max_length=8, null=True, verbose_name="Эмоджи"),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="enhancement_level",
            field=models.IntegerField(default=0, verbose_name="Уровень улучшения"),
        ),
        migrations.AddField(
            model_name="characteritem",
            name="equipped",
            field=models.BooleanField(default=False, verbose_name="Надето"),
        ),
        migrations.AlterField(
            model_name="character",
            name="exp_for_level_up",
            field=models.IntegerField(
                default=500, verbose_name="Опыт для достижения уровня"
            ),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.CreateModel(
            name="SkillEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property",
                    models.CharField(
                        choices=[
                            ("attack", "️⚔️Атака"),
                            ("defence", "🛡Защита"),
                            ("exp", "🔮Опыт"),
                            ("drop", "🍀Выпадение предметов"),
                            ("hunting_time", "⏳Время охоты"),
                        ],
                        default="attack",
                        max_length=16,
                        verbose_name="Свойство",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "in_percent",
                    models.BooleanField(default=False, verbose_name="В процентах"),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effect",
                        to="character.skill",
                        verbose_name="Умение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эффект",
                "verbose_name_plural": "Эффекты",
            },
        ),
        migrations.CreateModel(
            name="ClassEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("heavy_armor", "Тяжелая Броня"),
                            ("light_armor", "Легкая Броня"),
                            ("robe", "Мантия"),
                            ("sword", "Меч"),
                            ("staff", "Посох"),
                            ("blunt", "Дубина"),
                            ("dagger", "Кинжал"),
                            ("bracelet", "Браслет"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Вид экипировки",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equip",
                        to="character.characterclass",
                        verbose_name="Класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Классовая экипировка",
                "verbose_name_plural": "Классовые экипировки",
            },
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="character.skill",
                        verbose_name="Умение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение персонажа",
                "verbose_name_plural": "Умения персонажей",
            },
        ),
        migrations.CreateModel(
            name="CharacterRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.recipe",
                        verbose_name="Рецепт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт персонажа",
                "verbose_name_plural": "Рецепты персонажа",
            },
        ),
        migrations.CreateModel(
            name="CharacterEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permanent",
                    models.BooleanField(default=False, verbose_name="Постоянный"),
                ),
                (
                    "hunting_amount",
                    models.IntegerField(default=1, verbose_name="Количество охот"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="item.itemeffect",
                        verbose_name="Эффект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эффект персонажа",
                "verbose_name_plural": "Эффекты персонажа",
            },
        ),
        migrations.CreateModel(
            name="CharacterClassSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.characterclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="character.skill",
                        verbose_name="Умение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение класса",
                "verbose_name_plural": "Умения классов",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="effects",
            field=models.ManyToManyField(
                related_name="character_effects",
                through="character.CharacterEffect",
                to="item.itemeffect",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="recipes",
            field=models.ManyToManyField(
                related_name="character_recipes",
                through="character.CharacterRecipe",
                to="item.recipe",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="skills",
            field=models.ManyToManyField(
                related_name="character_skills",
                through="character.CharacterSkill",
                to="character.skill",
            ),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="skills",
            field=models.ManyToManyField(
                related_name="class_skills",
                through="character.CharacterClassSkill",
                to="character.skill",
            ),
        ),
    ]
