# Generated by Django 4.2.10 on 2024-02-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterclass",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
