# Generated by Django 4.2.10 on 2024-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0002_alter_characterclass_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterclass",
            name="armor_type",
            field=models.CharField(
                choices=[("heavy", "Тяжелая"), ("light", "Легкая"), ("robe", "Ткань")],
                default="heavy",
                max_length=16,
                verbose_name="Вид брони",
            ),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="weapon_type",
            field=models.CharField(
                choices=[
                    ("sword", "Меч"),
                    ("staff", "Посох"),
                    ("blunt", "Дубина"),
                    ("dagger", "Кинжал"),
                ],
                default="sword",
                max_length=16,
                verbose_name="Вид оружия",
            ),
        ),
    ]
