# Generated by Django 4.2.10 on 2024-03-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "character",
            "0002_skill_remove_characterclass_attack_level_increase_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactereffect",
            name="expired",
        ),
        migrations.AddField(
            model_name="charactereffect",
            name="hunting_amount",
            field=models.IntegerField(default=1, verbose_name="Количество охот"),
        ),
        migrations.AddField(
            model_name="charactereffect",
            name="permanent",
            field=models.BooleanField(default=False, verbose_name="Постоянный"),
        ),
    ]
