# Generated by Django 4.2.10 on 2024-03-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="kills",
            field=models.IntegerField(default=0, verbose_name="Убийств"),
        ),
    ]
