# Generated by Django 4.2.10 on 2024-03-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_add_etc_data"),
        (
            "character",
            "0002_skill_remove_characterclass_attack_level_increase_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "enhancement_level",
                    models.IntegerField(default=0, verbose_name="Уровень улучшения"),
                ),
                ("price", models.IntegerField(default=1, verbose_name="Стоимость")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_item",
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "sell_currency",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_currency",
                        to="item.etc",
                        verbose_name="Валюта продажи",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Продавец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет на Торговой Площадке",
                "verbose_name_plural": "Предметы на Торговой Площадке",
            },
        ),
    ]
