# Generated by Django 4.2.10 on 2024-03-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_character_kills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteritem",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
    ]
