# Generated by Django 4.2.10 on 2024-03-13 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_marketplaceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="premium_expired",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Окончание Премиума"
            ),
        ),
    ]
