# Generated by Django 4.2.10 on 2024-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_remove_charactereffect_expired_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classequipment",
            name="type",
            field=models.CharField(
                choices=[
                    ("heavy_armor", "Тяжелая Броня"),
                    ("light_armor", "Легкая Броня"),
                    ("robe", "Мантия"),
                    ("sword", "Меч"),
                    ("staff", "Посох"),
                    ("blunt", "Дубина"),
                    ("dagger", "Кинжал"),
                    ("bracelet", "Браслет"),
                ],
                max_length=16,
                null=True,
                verbose_name="Вид экипировки",
            ),
        ),
    ]
