# Generated by Django 4.2.10 on 2024-03-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0004_alter_characteritem_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="cooldown",
            field=models.TimeField(blank=True, null=True, verbose_name="Перезарядка"),
        ),
        migrations.AddField(
            model_name="skill",
            name="effect_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время действия"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="emoji",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Эмоджи"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="mana_cost",
            field=models.IntegerField(default=0, verbose_name="Мана кост"),
        ),
        migrations.AddField(
            model_name="skill",
            name="type",
            field=models.CharField(
                choices=[
                    ("passive", "Пассивная"),
                    ("toggle", "Переключаемая"),
                    ("active", "Активная"),
                ],
                default="passive",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
    ]
