# Generated by Django 4.2.10 on 2024-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0004_alter_classequipment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteritem",
            name="enhancement_level",
            field=models.IntegerField(default=0, verbose_name="Уровень улучшения"),
        ),
    ]
