# Generated by Django 4.2.10 on 2024-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "character",
            "0004_skill_alter_character_exp_for_level_up_skilleffect_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="drop_modifier",
            field=models.IntegerField(default=1, verbose_name="Модификатор дропа"),
        ),
        migrations.AddField(
            model_name="character",
            name="exp_modifier",
            field=models.IntegerField(default=1, verbose_name="Модмфикатор опыта"),
        ),
    ]
