# Generated by Django 4.2.10 on 2024-03-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0004_character_premium_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteritem",
            name="amount",
            field=models.IntegerField(default=1, verbose_name="Количество"),
        ),
    ]
