# Generated by Django 4.2.10 on 2024-03-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_effect_remove_itemeffect_amount_and_more"),
        ("character", "0005_alter_characteritem_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skilleffect",
            options={
                "verbose_name": "Эффект способности",
                "verbose_name_plural": "Эффекты способностей",
            },
        ),
        migrations.RemoveField(
            model_name="skilleffect",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="skilleffect",
            name="in_percent",
        ),
        migrations.RemoveField(
            model_name="skilleffect",
            name="property",
        ),
        migrations.AddField(
            model_name="skill",
            name="effects",
            field=models.ManyToManyField(
                through="character.SkillEffect",
                to="item.effect",
                verbose_name="Эффекты способностей",
            ),
        ),
        migrations.AddField(
            model_name="skilleffect",
            name="effect",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="item.effect",
                verbose_name="Эффект",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="skilleffect",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="character.skill",
                verbose_name="Способность",
            ),
        ),
    ]
