# Generated by Django 4.2.10 on 2024-02-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0005_character_drop_modifier_character_exp_modifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterclass",
            name="emoji",
            field=models.CharField(max_length=8, null=True, verbose_name="Эмоджи"),
        ),
    ]
