# Generated by Django 4.2.10 on 2024-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0005_skill_cooldown_skill_effect_time_skill_emoji_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="mana",
            field=models.IntegerField(default=20, verbose_name="Мана"),
        ),
        migrations.AddField(
            model_name="character",
            name="max_mana",
            field=models.IntegerField(default=20, verbose_name="Макс Мана"),
        ),
    ]
