# Generated by Django 4.2.10 on 2024-03-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0006_character_mana_character_max_mana"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterskill",
            name="turn_on",
            field=models.BooleanField(
                default=False, verbose_name="Активирован (Для переключаемых)"
            ),
        ),
    ]
