# Generated by Django 4.2.10 on 2024-03-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_effect_remove_itemeffect_amount_and_more"),
        (
            "character",
            "0006_alter_skilleffect_options_remove_skilleffect_amount_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactereffect",
            name="hunting_amount",
        ),
        migrations.RemoveField(
            model_name="charactereffect",
            name="permanent",
        ),
        migrations.AddField(
            model_name="charactereffect",
            name="hunting_minutes",
            field=models.IntegerField(default=240, verbose_name="Минут действия"),
        ),
        migrations.AlterField(
            model_name="character",
            name="effects",
            field=models.ManyToManyField(
                related_name="character_effects",
                through="character.CharacterEffect",
                to="item.effect",
            ),
        ),
        migrations.AlterField(
            model_name="charactereffect",
            name="effect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="item.effect",
                verbose_name="Эффект",
            ),
        ),
    ]
