# Generated by Django 4.2.10 on 2024-02-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0007_alter_craftingitem_options_and_more"),
        ("character", "0007_alter_skilleffect_property"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.recipe",
                        verbose_name="Рецепт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт персонажа",
                "verbose_name_plural": "Рецепты персонажа",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="recipes",
            field=models.ManyToManyField(
                related_name="character_recipes",
                through="character.CharacterRecipe",
                to="item.recipe",
            ),
        ),
    ]
