# Generated by Django 4.2.10 on 2024-03-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_effect_remove_itemeffect_amount_and_more"),
        ("character", "0007_remove_charactereffect_hunting_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skilleffect",
            name="effect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="item.effect",
                verbose_name="Эффект",
            ),
        ),
        migrations.AlterField(
            model_name="skilleffect",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.skill",
                verbose_name="Способность",
            ),
        ),
    ]
