# Generated by Django 4.2.10 on 2024-03-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_effect_remove_itemeffect_amount_and_more"),
        ("character", "0008_alter_skilleffect_effect_alter_skilleffect_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skilleffect",
            name="effect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="item.effect",
                verbose_name="Эффект",
            ),
        ),
        migrations.AlterField(
            model_name="skilleffect",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="character.skill",
                verbose_name="Способность",
            ),
        ),
    ]
