# Generated by Django 4.2.10 on 2024-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0009_remove_character_drop_modifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="health",
            field=models.IntegerField(default=20, verbose_name="Здоровье"),
        ),
        migrations.AddField(
            model_name="character",
            name="max_health",
            field=models.IntegerField(default=20, verbose_name="Макс здоровье"),
        ),
        migrations.AlterField(
            model_name="character",
            name="max_mana",
            field=models.IntegerField(default=20, verbose_name="Макс мана"),
        ),
    ]
