# Generated by Django 4.2.10 on 2024-03-19 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0009_alter_skilleffect_effect_alter_skilleffect_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactereffect",
            name="hunting_minutes",
        ),
        migrations.AddField(
            model_name="charactereffect",
            name="expired",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Окончание Эффекта"
            ),
        ),
    ]
