# Generated by Django 4.2.10 on 2024-03-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0010_alter_item_type"),
        ("character", "0009_characteritem_equipped"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="item.itemeffect",
                        verbose_name="Эффект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эффект персонажа",
                "verbose_name_plural": "Эффекты персонажа",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="effects",
            field=models.ManyToManyField(
                related_name="character_effects",
                through="character.CharacterEffect",
                to="item.itemeffect",
            ),
        ),
    ]
