# Generated by Django 4.2.10 on 2024-04-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_character_health_character_max_health_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="auto_use_hp_potion",
            field=models.BooleanField(
                default=False, verbose_name="Автоиспользование эликсиров здоровья"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="auto_use_mp_potion",
            field=models.BooleanField(
                default=False, verbose_name="Автоиспользование эликсиров маны"
            ),
        ),
    ]
