# Generated by Django 4.2.10 on 2024-03-01 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_charactereffect_character_effects"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactereffect",
            name="expired",
            field=models.DateTimeField(
                default=datetime.datetime(2100, 12, 31, 0, 0),
                verbose_name="Дата окончания эффекта",
            ),
        ),
    ]
