# Generated by Django 4.2.10 on 2024-03-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clan", "0003_alter_clanrequest_character"),
        ("character", "0010_remove_charactereffect_hunting_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="clan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clan.clan",
                verbose_name="Клан",
            ),
        ),
    ]
