# Generated by Django 4.2.10 on 2024-04-02 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0011_character_auto_use_hp_potion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="pvp_mode_expired",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Окончание PvP режима"
            ),
        ),
    ]
