# Generated by Django 4.2.10 on 2024-04-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0012_character_pvp_mode_expired"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
                (
                    "character_recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.characterrecipe",
                        verbose_name="Рецепт Персонажа",
                    ),
                ),
            ],
        ),
    ]
