# Generated by Django 4.2.10 on 2024-04-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0013_recipeshare"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeshare",
            options={
                "verbose_name": "Рецепт на Торговой Площадке",
                "verbose_name_plural": "Рецпты на Торговой Площадке",
            },
        ),
    ]
