# Generated by Django 4.2.10 on 2024-04-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0014_alter_recipeshare_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="accuracy",
            field=models.IntegerField(default=10, verbose_name="Точность"),
        ),
        migrations.AddField(
            model_name="character",
            name="crit_power",
            field=models.IntegerField(default=100, verbose_name="Сила Крита"),
        ),
        migrations.AddField(
            model_name="character",
            name="crit_rate",
            field=models.IntegerField(default=10, verbose_name="Шанс Крита"),
        ),
        migrations.AddField(
            model_name="character",
            name="evasion",
            field=models.IntegerField(default=10, verbose_name="Уклонение"),
        ),
        migrations.AlterField(
            model_name="character",
            name="attack",
            field=models.IntegerField(default=10, verbose_name="Атака"),
        ),
        migrations.AlterField(
            model_name="character",
            name="defence",
            field=models.IntegerField(default=10, verbose_name="Защита"),
        ),
    ]
