# Generated by Django 4.2.10 on 2024-04-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0015_character_accuracy_character_crit_power_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="crit_rate",
            field=models.IntegerField(default=50, verbose_name="Шанс Крита"),
        ),
    ]
