# Generated by Django 4.2.10 on 2024-04-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0016_alter_character_crit_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="skill_points",
            field=models.IntegerField(default=0, verbose_name="Очки Характеристик"),
        ),
    ]
