# Generated by Django 4.2.10 on 2024-04-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0017_character_skill_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="hunting_end",
        ),
        migrations.RemoveField(
            model_name="character",
            name="max_hunting_time",
        ),
    ]
