# Generated by Django 4.2.10 on 2024-04-17 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0011_alter_bagitem_bag_alter_bagitem_item_and_more"),
        ("character", "0018_remove_character_hunting_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skilleffect",
            name="effect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="item.effect",
                verbose_name="Эффект",
            ),
        ),
        migrations.AlterField(
            model_name="skilleffect",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="character.skill",
                verbose_name="Способность",
            ),
        ),
        migrations.CreateModel(
            name="Power",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.effect",
                        verbose_name="Эффект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сила",
                "verbose_name_plural": "Силы",
            },
        ),
        migrations.CreateModel(
            name="CharacterPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "characteristic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.power",
                        verbose_name="Сила",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сила персонажа",
                "verbose_name_plural": "Силы персонажей",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="powers",
            field=models.ManyToManyField(
                related_name="character_power",
                through="character.CharacterPower",
                to="character.power",
            ),
        ),
    ]
