# Generated by Django 4.2.10 on 2024-04-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0019_alter_skilleffect_effect_alter_skilleffect_skill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="crit_power",
            field=models.IntegerField(default=50, verbose_name="Сила Крита"),
        ),
    ]
