# Generated by Django 4.2.10 on 2024-04-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0020_alter_character_crit_power"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterpower",
            old_name="characteristic",
            new_name="power",
        ),
    ]
