# Generated by Django 4.2.10 on 2024-04-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0021_rename_characteristic_characterpower_power"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="health",
            field=models.IntegerField(default=24, verbose_name="Здоровье"),
        ),
        migrations.AlterField(
            model_name="character",
            name="mana",
            field=models.IntegerField(default=16, verbose_name="Мана"),
        ),
        migrations.AlterField(
            model_name="character",
            name="max_health",
            field=models.IntegerField(default=24, verbose_name="Макс здоровье"),
        ),
        migrations.AlterField(
            model_name="character",
            name="max_mana",
            field=models.IntegerField(default=16, verbose_name="Макс мана"),
        ),
    ]
