# Generated by Django 4.2.10 on 2024-02-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Имя")),
                (
                    "description",
                    models.CharField(max_length=256, verbose_name="Описание"),
                ),
                (
                    "sell_price",
                    models.IntegerField(default=0, verbose_name="Стоимость продажи"),
                ),
                (
                    "buy_price",
                    models.IntegerField(default=0, verbose_name="Стоимость покупки"),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("common", "️⚪️ Обычный"),
                            ("uncommon", "🟤 Необычный"),
                            ("rare", "🔵 Редкий"),
                            ("legendary", "🟠 Легендарный"),
                            ("epic", "🔴 Эпический"),
                        ],
                        default="common",
                        max_length=16,
                        verbose_name="Ранг",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("armor", "Броня"),
                            ("weapon", "Оружие"),
                            ("talisman", "Талисман"),
                            ("material", "Ресурс"),
                            ("scroll", "Свиток"),
                            ("etc", "Разное"),
                        ],
                        default="armor",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "armor_type",
                    models.CharField(
                        choices=[
                            ("heavy", "Тяжелая"),
                            ("light", "Легкая"),
                            ("robe", "Ткань"),
                        ],
                        default="heavy",
                        max_length=16,
                        verbose_name="Вид брони",
                    ),
                ),
            ],
            options={
                "verbose_name": "Броня",
                "verbose_name_plural": "Броня",
            },
            bases=("item.item",),
        ),
        migrations.CreateModel(
            name="Etc",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("armor", "Броня"),
                            ("weapon", "Оружие"),
                            ("talisman", "Талисман"),
                            ("material", "Ресурс"),
                            ("scroll", "Свиток"),
                            ("etc", "Разное"),
                        ],
                        default="etc",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разное",
                "verbose_name_plural": "Разное",
            },
            bases=("item.item",),
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("armor", "Броня"),
                            ("weapon", "Оружие"),
                            ("talisman", "Талисман"),
                            ("material", "Ресурс"),
                            ("scroll", "Свиток"),
                            ("etc", "Разное"),
                        ],
                        default="material",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурс",
                "verbose_name_plural": "Ресурсы",
            },
            bases=("item.item",),
        ),
        migrations.CreateModel(
            name="Scroll",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("armor", "Броня"),
                            ("weapon", "Оружие"),
                            ("talisman", "Талисман"),
                            ("material", "Ресурс"),
                            ("scroll", "Свиток"),
                            ("etc", "Разное"),
                        ],
                        default="scroll",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Свиток",
                "verbose_name_plural": "Свитки",
            },
            bases=("item.item",),
        ),
        migrations.CreateModel(
            name="Talisman",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("armor", "Броня"),
                            ("weapon", "Оружие"),
                            ("talisman", "Талисман"),
                            ("material", "Ресурс"),
                            ("scroll", "Свиток"),
                            ("etc", "Разное"),
                        ],
                        default="talisman",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Талисман",
                "verbose_name_plural": "Талисманы",
            },
            bases=("item.item",),
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("armor", "Броня"),
                            ("weapon", "Оружие"),
                            ("talisman", "Талисман"),
                            ("material", "Ресурс"),
                            ("scroll", "Свиток"),
                            ("etc", "Разное"),
                        ],
                        default="weapon",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "weapon_type",
                    models.CharField(
                        choices=[
                            ("sword", "Меч"),
                            ("staff", "Посох"),
                            ("blunt", "Дубина"),
                            ("dagger", "Кинжал"),
                        ],
                        default="sword",
                        max_length=16,
                        verbose_name="Вид оружия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оружие",
                "verbose_name_plural": "Оружия",
            },
            bases=("item.item",),
        ),
    ]
