# Generated by Django 4.2.10 on 2024-02-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property",
                    models.CharField(
                        choices=[
                            ("attack", "️Атака"),
                            ("defence", "Защита"),
                            ("exp", "Опыт"),
                            ("drop", "Выпадение предметов"),
                            ("hunting_time", "Время охоты"),
                        ],
                        default="attack",
                        max_length=16,
                        verbose_name="Свойство",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "in_percent",
                    models.BooleanField(default=False, verbose_name="В процентах"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effect",
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эффект предмета",
                "verbose_name_plural": "Эффекты предметов",
            },
        ),
    ]
