# Generated by Django 4.2.10 on 2024-03-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_equipment_potion_remove_armor_armor_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="potion",
            name="effect_time",
        ),
    ]
