# Generated by Django 4.2.10 on 2024-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_add_etc_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="effect",
            name="property",
            field=models.CharField(
                choices=[
                    ("attack", "️⚔️Атака"),
                    ("defence", "🛡Защита"),
                    ("exp", "🔮Опыт"),
                    ("drop", "🍀Выпадение предметов"),
                    ("hunting_time", "⏳Время охоты"),
                    ("pvp", "🩸Победа в PvP"),
                    ("mass_attack", "⚡️Массовая Атака"),
                    ("no_death_exp", "🪦Без потери опыта при смерти"),
                    ("evasion", "🥾Шанс избежать PvP"),
                ],
                default="attack",
                max_length=16,
                verbose_name="Свойство",
            ),
        ),
        migrations.AlterField(
            model_name="talisman",
            name="talisman_type",
            field=models.CharField(
                choices=[
                    ("attack", "️⚔️Атака"),
                    ("defence", "🛡Защита"),
                    ("exp", "🔮Опыт"),
                    ("drop", "🍀Выпадение предметов"),
                    ("hunting_time", "⏳Время охоты"),
                    ("pvp", "🩸Победа в PvP"),
                    ("mass_attack", "⚡️Массовая Атака"),
                    ("no_death_exp", "🪦Без потери опыта при смерти"),
                    ("evasion", "🥾Шанс избежать PvP"),
                ],
                default="attack",
                max_length=16,
                verbose_name="Вид талисмана",
            ),
        ),
    ]
