# Generated by Django 4.2.10 on 2024-03-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_add_etc_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Effect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property",
                    models.CharField(
                        choices=[
                            ("attack", "️⚔️Атака"),
                            ("defence", "🛡Защита"),
                            ("exp", "🔮Опыт"),
                            ("drop", "🍀Выпадение предметов"),
                            ("hunting_time", "⏳Время охоты"),
                        ],
                        default="attack",
                        max_length=16,
                        verbose_name="Свойство",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "in_percent",
                    models.BooleanField(default=False, verbose_name="В процентах"),
                ),
            ],
            options={
                "verbose_name": "Эффект",
                "verbose_name_plural": "Эффекты",
            },
        ),
        migrations.RemoveField(
            model_name="itemeffect",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="itemeffect",
            name="in_percent",
        ),
        migrations.RemoveField(
            model_name="itemeffect",
            name="property",
        ),
        migrations.AlterField(
            model_name="itemeffect",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="item.item",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="effects",
            field=models.ManyToManyField(
                through="item.ItemEffect",
                to="item.effect",
                verbose_name="Эффекты предметов",
            ),
        ),
        migrations.AddField(
            model_name="itemeffect",
            name="effect",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="item.effect",
                verbose_name="Эффект",
            ),
            preserve_default=False,
        ),
    ]
