# Generated by Django 4.2.10 on 2024-03-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_remove_potion_effect_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bag",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мешок",
                "verbose_name_plural": "Мешки",
            },
            bases=("item.item",),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("potion", "Эликсир"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("bag", "Мешок"),
                    ("etc", "Разное"),
                ],
                default="etc",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.CreateModel(
            name="BagItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chance", models.FloatField(default=1, verbose_name="Шанс")),
                (
                    "bag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bag_items",
                        to="item.item",
                        verbose_name="Мешок",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="item_in_bag",
                        to="item.item",
                        verbose_name="Возможный предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет в мешке",
                "verbose_name_plural": "Предметы в мешке",
            },
        ),
    ]
