# Generated by Django 4.2.10 on 2024-02-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_item_crafting_level_craftingitems_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CraftingItems",
            new_name="CraftingItem",
        ),
    ]
