# Generated by Django 4.2.10 on 2024-03-20 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_effect_remove_itemeffect_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="potion",
            name="effect_time",
            field=models.TimeField(
                default=datetime.time(12, 0), verbose_name="Время действия"
            ),
        ),
    ]
