# Generated by Django 4.2.10 on 2024-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_rename_craftingitems_craftingitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="crafting_items",
            field=models.ManyToManyField(
                related_name="items_for_craft",
                through="item.CraftingItem",
                to="item.item",
                verbose_name="Предметы для крафта",
            ),
        ),
    ]
