# Generated by Django 4.2.10 on 2024-03-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_bag_alter_item_type_bagitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bagitem",
            name="bag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bag_items",
                to="item.bag",
                verbose_name="Мешок",
            ),
        ),
    ]
