# Generated by Django 4.2.10 on 2024-03-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_alter_bagitem_bag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="grade",
        ),
    ]
