# Generated by Django 4.2.10 on 2024-02-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_alter_item_crafting_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="craftingitem",
            name="crafting_item",
        ),
        migrations.RemoveField(
            model_name="craftingitem",
            name="used_item",
        ),
        migrations.RemoveField(
            model_name="item",
            name="crafting_items",
        ),
        migrations.RemoveField(
            model_name="item",
            name="crafting_level",
        ),
        migrations.AddField(
            model_name="craftingitem",
            name="material",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="recipes",
                to="item.material",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="armor",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                default="armor",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="etc",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                default="etc",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="itemeffect",
            name="property",
            field=models.CharField(
                choices=[
                    ("attack", "️⚔️Атака"),
                    ("defence", "🛡Защита"),
                    ("exp", "🔮Опыт"),
                    ("drop", "🍀Выпадение предметов"),
                    ("hunting_time", "⏳Время охоты"),
                ],
                default="attack",
                max_length=16,
                verbose_name="Свойство",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                default="material",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="scroll",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                default="scroll",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="talisman",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                default="talisman",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                default="weapon",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("armor", "Броня"),
                            ("weapon", "Оружие"),
                            ("talisman", "Талисман"),
                            ("recipe", "Рецепт"),
                            ("material", "Ресурс"),
                            ("scroll", "Свиток"),
                            ("etc", "Разное"),
                        ],
                        default="recipe",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                (
                    "chance",
                    models.IntegerField(default=100, verbose_name="Шанс изготовления"),
                ),
                (
                    "create",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_create",
                        to="item.item",
                        verbose_name="Изготавливает",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
            bases=("item.item",),
        ),
        migrations.AddField(
            model_name="craftingitem",
            name="recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="item.recipe",
                verbose_name="Рецепт",
            ),
        ),
    ]
