# Generated by Django 4.2.10 on 2024-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_potion_effect_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="effect",
            name="slug",
            field=models.CharField(
                choices=[
                    ("potion", "🌡Эликсир"),
                    ("skill", "↗️Способность"),
                    ("item", "🎒Предмет"),
                    ("fatigue", "♦️Усталость"),
                ],
                default="potion",
                max_length=16,
                verbose_name="Вид эффекта",
            ),
        ),
    ]
