# Generated by Django 4.2.10 on 2024-03-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_effect_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(
                default="Нет описания предмета", max_length=256, verbose_name="Описание"
            ),
        ),
    ]
