# Generated by Django 4.2.10 on 2024-02-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_remove_craftingitem_crafting_item_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="craftingitem",
            options={
                "verbose_name": "Предмет изготовлени",
                "verbose_name_plural": "Предметы изготовления",
            },
        ),
        migrations.AlterField(
            model_name="craftingitem",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="recipes",
                to="item.material",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="craftingitem",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="item.recipe",
                verbose_name="Рецепт",
            ),
        ),
    ]
