# Generated by Django 4.2.10 on 2024-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_remove_item_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="enhancement_level",
            field=models.IntegerField(default=0, verbose_name="Уровень улучшения"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("heavy_armor", "Тяжелая Броня"),
                    ("light_armor", "Легкая Броня"),
                    ("robe", "Мантия"),
                    ("sword", "Меч"),
                    ("staff", "Посох"),
                    ("blunt", "Дубина"),
                    ("dagger", "Кинжал"),
                    ("bracelet", "Браслет"),
                ],
                default="heavy_armor",
                max_length=16,
                verbose_name="Вид экипировки",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "🛡Броня"),
                    ("weapon", "⚔️Оружие"),
                    ("potion", "🌡Эликсир"),
                    ("talisman", "⭐️Талисман"),
                    ("recipe", "📕Рецепт"),
                    ("material", "🪵Ресурс"),
                    ("scroll", "📜Свиток"),
                    ("bag", "📦Мешок"),
                    ("etc", "Разное"),
                ],
                default="etc",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
    ]
