# Generated by Django 4.2.10 on 2024-03-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0007_equipment_enhancement_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="enhancement_level",
        ),
    ]
