# Generated by Django 4.2.10 on 2024-03-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_remove_charactereffect_hunting_minutes_and_more"),
        ("item", "0007_alter_item_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.characterclass",
                        verbose_name="Требуемый класс",
                    ),
                ),
                (
                    "required_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_required",
                        to="character.skill",
                        verbose_name="Требуемое умение",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_give",
                        to="character.skill",
                        verbose_name="Получаемое умение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
            bases=("item.item",),
        ),
    ]
