# Generated by Django 4.2.10 on 2024-03-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0007_alter_craftingitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="armor",
            name="type",
        ),
        migrations.RemoveField(
            model_name="etc",
            name="type",
        ),
        migrations.RemoveField(
            model_name="material",
            name="type",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="type",
        ),
        migrations.RemoveField(
            model_name="scroll",
            name="type",
        ),
        migrations.RemoveField(
            model_name="talisman",
            name="type",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="type",
        ),
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                default="etc",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
    ]
