# Generated by Django 4.2.10 on 2024-04-15 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0007_alter_craftingitem_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bracelet",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Браслет",
                "verbose_name_plural": "Браслеты",
            },
            bases=("item.equipment",),
        ),
    ]
