# Generated by Django 4.2.10 on 2024-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0008_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="required_level",
            field=models.IntegerField(default=1, verbose_name="Требуемый уровень"),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "🛡Броня"),
                    ("book", "📕Книга"),
                    ("weapon", "⚔️Оружие"),
                    ("potion", "🌡Эликсир"),
                    ("talisman", "⭐️Талисман"),
                    ("recipe", "📕Рецепт"),
                    ("material", "🪵Ресурс"),
                    ("scroll", "📜Свиток"),
                    ("bag", "📦Мешок"),
                    ("etc", "Разное"),
                ],
                default="etc",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="scroll",
            name="enhance_type",
            field=models.CharField(
                choices=[
                    ("armor", "🛡Броня"),
                    ("book", "📕Книга"),
                    ("weapon", "⚔️Оружие"),
                    ("potion", "🌡Эликсир"),
                    ("talisman", "⭐️Талисман"),
                    ("recipe", "📕Рецепт"),
                    ("material", "🪵Ресурс"),
                    ("scroll", "📜Свиток"),
                    ("bag", "📦Мешок"),
                    ("etc", "Разное"),
                ],
                default="weapon",
                max_length=16,
                verbose_name="Улучшаемый тип",
            ),
        ),
    ]
