# Generated by Django 4.2.10 on 2024-03-01 11:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0008_remove_armor_type_remove_etc_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Potion",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                (
                    "effect_time",
                    models.TimeField(
                        default=datetime.time(12, 0), verbose_name="Время действия"
                    ),
                ),
            ],
            options={
                "verbose_name": "Эликсир",
                "verbose_name_plural": "Эликсиры",
            },
            bases=("item.item",),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("elixir", "Эликсир"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                default="etc",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
    ]
