# Generated by Django 4.2.10 on 2024-03-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0009_potion_alter_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("potion", "Эликсир"),
                    ("talisman", "Талисман"),
                    ("recipe", "Рецепт"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                default="etc",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
    ]
