# Generated by Django 4.2.10 on 2024-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0009_alter_bagitem_chance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bagitem",
            name="chance",
            field=models.IntegerField(default=1, verbose_name="Количество в мешке"),
        ),
    ]
