# Generated by Django 4.2.10 on 2024-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0010_alter_bagitem_chance"),
    ]

    operations = [
        migrations.AddField(
            model_name="scroll",
            name="enhance_type",
            field=models.CharField(
                choices=[
                    ("armor", "🛡Броня"),
                    ("weapon", "⚔️Оружие"),
                    ("potion", "🌡Эликсир"),
                    ("talisman", "⭐️Талисман"),
                    ("recipe", "📕Рецепт"),
                    ("material", "🪵Ресурс"),
                    ("scroll", "📜Свиток"),
                    ("bag", "📦Мешок"),
                    ("etc", "Разное"),
                ],
                default="weapon",
                max_length=16,
                verbose_name="Улучшаемый тип",
            ),
        ),
    ]
