# Generated by Django 4.2.10 on 2024-04-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0011_alter_bagitem_bag_alter_bagitem_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="effect",
            name="slug",
            field=models.CharField(
                choices=[
                    ("potion", "🌡Эликсир"),
                    ("skill", "↗️Способность"),
                    ("item", "🎒Предмет"),
                    ("fatigue", "♦️Усталость"),
                    ("power", "⚡️Сила"),
                ],
                default="potion",
                max_length=16,
                verbose_name="Вид эффекта",
            ),
        ),
    ]
