# Generated by Django 4.2.10 on 2024-02-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseGameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Имя")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "basegamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.basegamemodel",
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                ("exp", models.IntegerField(default=0, verbose_name="Опыт")),
                (
                    "exp_for_level_up",
                    models.IntegerField(
                        default=100, verbose_name="Опыт для достижения уровня"
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
            },
            bases=("game.basegamemodel",),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "basegamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.basegamemodel",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=256, verbose_name="Описание"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("armor", "Броня"),
                            ("weapon", "Оружие"),
                            ("talisman", "Талисман"),
                            ("material", "Ресурс"),
                            ("scroll", "Свиток"),
                        ],
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
            bases=("game.basegamemodel",),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "basegamemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game.basegamemodel",
                    ),
                ),
                (
                    "required_power",
                    models.IntegerField(verbose_name="Требуемая сила персонажа"),
                ),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Лоакации",
            },
            bases=("game.basegamemodel",),
        ),
        migrations.CreateModel(
            name="LocationDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(
                        default=1, verbose_name="Минимальное количество"
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        default=1, verbose_name="Максимальное количество"
                    ),
                ),
                (
                    "chance",
                    models.IntegerField(default=1, verbose_name="Шанс в процентах"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.item",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.location",
                        verbose_name="Локация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дроп в локации",
                "verbose_name_plural": "Дроп в локациях",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="drop",
            field=models.ManyToManyField(
                related_name="drop", through="game.LocationDrop", to="game.item"
            ),
        ),
        migrations.CreateModel(
            name="CharacterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=1, verbose_name="Количество")),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет персонажа",
                "verbose_name_plural": "Предметы персонажа",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="items",
            field=models.ManyToManyField(
                related_name="items", through="game.CharacterItem", to="game.item"
            ),
        ),
    ]
