# Generated by Django 4.2.10 on 2024-02-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="power",
            field=models.IntegerField(default=100, verbose_name="Боевая мощь"),
        ),
    ]
