# Generated by Django 4.2.10 on 2024-02-21 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="current_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.location",
                verbose_name="Текущая локация",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="hunting_begin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало охоты"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="hunting_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Конец охоты"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="job_id",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="ID шедулера напоминания об окончании охоты",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="max_hunting_time",
            field=models.TimeField(
                default=datetime.time(4, 0), verbose_name="Максимальное время охоты"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="power",
            field=models.IntegerField(default=100, verbose_name="Боевая мощь"),
        ),
        migrations.AddField(
            model_name="item",
            name="buy_price",
            field=models.IntegerField(default=0, verbose_name="Стоимость покупки"),
        ),
        migrations.AddField(
            model_name="item",
            name="sell_price",
            field=models.IntegerField(default=0, verbose_name="Стоимость продажи"),
        ),
        migrations.AddField(
            model_name="location",
            name="exp",
            field=models.IntegerField(
                default=100, verbose_name="Количество опыта в час"
            ),
        ),
        migrations.AlterField(
            model_name="characteritem",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("talisman", "Талисман"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="locationdrop",
            name="chance",
            field=models.IntegerField(default=1, verbose_name="Шанс в процентах в час"),
        ),
        migrations.AlterField(
            model_name="locationdrop",
            name="max_amount",
            field=models.IntegerField(
                default=1, verbose_name="Максимальное количество в час"
            ),
        ),
        migrations.AlterField(
            model_name="locationdrop",
            name="min_amount",
            field=models.IntegerField(
                default=1, verbose_name="Минимальное количество в час"
            ),
        ),
    ]
