# Generated by Django 4.2.10 on 2024-02-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_character_current_location_character_hunting_begin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="grade",
            field=models.CharField(
                choices=[
                    ("common", "️⚪️ Обычный"),
                    ("uncommon", "🟤 Необычный"),
                    ("rare", "🔵 Редкий"),
                    ("legendary", "🟠 Легендарный"),
                    ("epic", "🔴 Эпический"),
                ],
                default="common",
                max_length=16,
                verbose_name="Ранг",
            ),
        ),
    ]
