# Generated by Django 4.2.10 on 2024-02-21 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_character_power"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="current_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.location",
                verbose_name="Текущая локация",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="hunting_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время окончания охоты"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="max_hunting_time",
            field=models.TimeField(
                default=datetime.time(4, 0), verbose_name="Максимальное время охоты"
            ),
        ),
    ]
