# Generated by Django 4.2.10 on 2024-02-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_character_current_location_character_hunting_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="exp",
            field=models.IntegerField(
                default=100, verbose_name="Количество опыта в час"
            ),
        ),
        migrations.AlterField(
            model_name="locationdrop",
            name="chance",
            field=models.IntegerField(default=1, verbose_name="Шанс в процентах в час"),
        ),
        migrations.AlterField(
            model_name="locationdrop",
            name="max_amount",
            field=models.IntegerField(
                default=1, verbose_name="Максимальное количество в час"
            ),
        ),
        migrations.AlterField(
            model_name="locationdrop",
            name="min_amount",
            field=models.IntegerField(
                default=1, verbose_name="Минимальное количество в час"
            ),
        ),
    ]
