# Generated by Django 4.2.10 on 2024-02-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_location_exp_alter_locationdrop_chance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="buy_price",
            field=models.IntegerField(default=0, verbose_name="Стоимость покупки"),
        ),
        migrations.AddField(
            model_name="item",
            name="sell_price",
            field=models.IntegerField(default=0, verbose_name="Стоимость продажи"),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("armor", "Броня"),
                    ("weapon", "Оружие"),
                    ("talisman", "Талисман"),
                    ("material", "Ресурс"),
                    ("scroll", "Свиток"),
                    ("etc", "Разное"),
                ],
                max_length=16,
                verbose_name="Тип",
            ),
        ),
    ]
