# Generated by Django 4.2.10 on 2024-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_item_buy_price_item_sell_price_alter_item_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="hunting_time",
        ),
        migrations.AddField(
            model_name="character",
            name="hunting_begin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало охоты"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="hunting_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Конец охоты"
            ),
        ),
    ]
