# Generated by Django 4.2.10 on 2024-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_remove_character_hunting_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteritem",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
    ]
