# Generated by Django 4.2.10 on 2024-02-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_character_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="job_id",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="ID шедулера напоминания об окончании охоты",
            ),
        ),
    ]
