# Generated by Django 4.2.10 on 2024-03-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0010_remove_charactereffect_hunting_minutes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Эмоджи"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Нет описания", max_length=128, verbose_name="Описание"
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                (
                    "reputation",
                    models.IntegerField(default=0, verbose_name="Репутация"),
                ),
                ("place", models.IntegerField(default=10, verbose_name="Мест в клане")),
                (
                    "by_request",
                    models.BooleanField(default=True, verbose_name="Вход по заявкам"),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="character.character",
                        verbose_name="Лидер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клан",
                "verbose_name_plural": "Кланы",
            },
        ),
        migrations.CreateModel(
            name="ClanWar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(default=False, verbose_name="Война принята"),
                ),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="war_sent",
                        to="clan.clan",
                        verbose_name="Клан",
                    ),
                ),
                (
                    "enemy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="war_request",
                        to="clan.clan",
                        verbose_name="Враг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клановая война",
                "verbose_name_plural": "Клановые войны",
            },
        ),
        migrations.CreateModel(
            name="ClanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Текст заявки",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        unique=True,
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clan.clan",
                        verbose_name="Клан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
