# Generated by Django 4.2.10 on 2024-03-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_remove_charactereffect_hunting_minutes_and_more"),
        ("clan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clan",
            name="requests",
            field=models.ManyToManyField(
                related_name="clan_request",
                through="clan.ClanRequest",
                to="character.character",
                verbose_name="Заявки",
            ),
        ),
        migrations.AddField(
            model_name="clan",
            name="wars",
            field=models.ManyToManyField(
                through="clan.ClanWar", to="clan.clan", verbose_name="Войны"
            ),
        ),
        migrations.AlterField(
            model_name="clan",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="clan_leader",
                to="character.character",
                verbose_name="Лидер",
            ),
        ),
    ]
