# Generated by Django 4.2.10 on 2024-04-03 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_alter_effect_property_alter_talisman_talisman_type"),
        ("clan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClanBoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Имя")),
                (
                    "respawn",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Время Респауна"
                    ),
                ),
                (
                    "required_power",
                    models.IntegerField(
                        default=100, verbose_name="Необходимая сила клана"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClanBossDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(
                        default=1, verbose_name="Минимальное количество"
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        default=1, verbose_name="Максимальное количество"
                    ),
                ),
                (
                    "chance",
                    models.FloatField(
                        default=1, verbose_name="Шанс в процентах в минуту"
                    ),
                ),
                (
                    "clan_boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clan.clanboss",
                        verbose_name="Клановый босс",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clanboss",
            name="drop",
            field=models.ManyToManyField(
                related_name="clan_boss_drop",
                through="clan.ClanBossDrop",
                to="item.item",
            ),
        ),
    ]
