# Generated by Django 4.2.10 on 2024-03-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_remove_charactereffect_hunting_minutes_and_more"),
        ("clan", "0002_clan_requests_clan_wars_alter_clan_leader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clanrequest",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="character.character",
                verbose_name="Персонаж",
            ),
        ),
    ]
