# Generated by Django 4.2.10 on 2024-04-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0014_alter_recipeshare_options"),
        ("clan", "0003_alter_clanboss_options_clanwarehouse_clan_warehouse"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClanBossCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clan.clanboss",
                        verbose_name="Клановый босс",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж в рейде",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж в рейде",
                "verbose_name_plural": "Персонажи в рейде",
            },
        ),
        migrations.AddField(
            model_name="clanboss",
            name="characters",
            field=models.ManyToManyField(
                through="clan.ClanBossCharacter", to="character.character"
            ),
        ),
    ]
