# Generated by Django 4.2.10 on 2024-04-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clan", "0004_clanbosscharacter_clanboss_characters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClanBossClan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clan.clanboss",
                        verbose_name="Клановый босс",
                    ),
                ),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clan.clan",
                        verbose_name="Клан в рейде",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клан в рейде",
                "verbose_name_plural": "Кланы в рейде",
            },
        ),
        migrations.AddField(
            model_name="clanboss",
            name="clans",
            field=models.ManyToManyField(through="clan.ClanBossClan", to="clan.clan"),
        ),
    ]
