# Generated by Django 4.2.10 on 2024-04-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clan", "0005_clanbossclan_clanboss_clans"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clanbossdrop",
            options={
                "verbose_name": "Трофей с босса",
                "verbose_name_plural": "Трофеи с босса",
            },
        ),
    ]
