EXP_RATE = 2
DROP_RATE = 2
DROP_AMOUNT_RATE = 2
EXP_DECREASE_PERCENT = 10
HEALTH_REGENERATION_IN_MINUTE = 1
MANA_REGENERATION_IN_MINUTE = 1


LOCATION_STAT_DIFFERENCE = 3

TOGGLE_SKILL_COST_IN_PVP_MODIFIER = 5

# Эффекты в процентах добавляются первыми
IN_PERCENT_MODIFIER_FIRST = True

EXP_FOR_LEVEL_UP_MULTIPLIER = 1.5
ATTACK_INCREASE_LEVEL_UP = 3
DEFENCE_INCREASE_LEVEL_UP = 3
HEALTH_INCREASE_LEVEL_UP = 15
MANA_INCREASE_LEVEL_UP = 10

ENHANCE_CHANCE = [
    30,
    25,
    20,
    15,
    10,
    7,
    5,
    3,
]

ENHANCE_INCREASE = 4
ENHANCE_IN_PERCENT_INCREASE = 10

MARKETPLACE_TAX = 10
MAX_LOT_AMOUNT = 5

PREMIUM_EXP_MODIFIER = 2
PREMIUM_DROP_MODIFIER = 1.5
PREMIUM_DEATH_EXP_MODIFIER = 0.5


WAR_EXP_DECREASE_PERCENT = 1
WAR_END_REPUTATION_COST = 100
REPUTATION_AMOUNT_BY_LEVEL = 5
