# Generated by Django 4.2.10 on 2024-03-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseLocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Имя")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "baselocationmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="location.baselocationmodel",
                    ),
                ),
                (
                    "attack",
                    models.IntegerField(verbose_name="Требуемая атака персонажа"),
                ),
                (
                    "defence",
                    models.IntegerField(verbose_name="Требуемая защита персонажа"),
                ),
                (
                    "exp",
                    models.IntegerField(
                        default=1, verbose_name="Количество опыта в минуту"
                    ),
                ),
                (
                    "place",
                    models.IntegerField(default=10, verbose_name="Мест в локации"),
                ),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
            bases=("location.baselocationmodel",),
        ),
        migrations.CreateModel(
            name="LocationDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(
                        default=1, verbose_name="Минимальное количество"
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        default=1, verbose_name="Максимальное количество"
                    ),
                ),
                (
                    "chance",
                    models.FloatField(
                        default=1, verbose_name="Шанс в процентах в минуту"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.location",
                        verbose_name="Локация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дроп в локации",
                "verbose_name_plural": "Дроп в локациях",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="drop",
            field=models.ManyToManyField(
                related_name="drop", through="location.LocationDrop", to="item.item"
            ),
        ),
    ]
