# Generated by Django 4.2.10 on 2024-04-18 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item", "0001_initial"),
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HuntingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Имя")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "exp",
                    models.IntegerField(
                        default=1, verbose_name="Количество опыта в минуту"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationBoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Имя")),
                (
                    "respawn",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Время Респауна"
                    ),
                ),
                (
                    "required_power",
                    models.IntegerField(
                        default=100, verbose_name="Необходимая сила персонажа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Босс Локации",
                "verbose_name_plural": "Боссы Локации",
            },
        ),
        migrations.CreateModel(
            name="Dungeon",
            fields=[
                (
                    "huntingzone_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="location.huntingzone",
                    ),
                ),
                (
                    "min_level",
                    models.IntegerField(
                        default=1, verbose_name="Минимальный Уровень Персонажа"
                    ),
                ),
                (
                    "max_level",
                    models.IntegerField(
                        default=1, verbose_name="Максимальный Уровень Персонажа"
                    ),
                ),
                (
                    "cooldown_hours",
                    models.IntegerField(
                        default=24, verbose_name="Ожидание часов для повторного входа"
                    ),
                ),
                (
                    "hunting_hours",
                    models.IntegerField(
                        default=4, verbose_name="Часов максимальной охоты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подземелье",
                "verbose_name_plural": "Подземелья",
            },
            bases=("location.huntingzone",),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "huntingzone_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="location.huntingzone",
                    ),
                ),
                (
                    "place",
                    models.IntegerField(default=10, verbose_name="Мест в локации"),
                ),
                (
                    "required_power",
                    models.IntegerField(
                        default=100, verbose_name="Требуемая сила персонажа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
            bases=("location.huntingzone",),
        ),
        migrations.CreateModel(
            name="LocationBossDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(
                        default=1, verbose_name="Минимальное количество"
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        default=1, verbose_name="Максимальное количество"
                    ),
                ),
                (
                    "chance",
                    models.FloatField(
                        default=1, verbose_name="Шанс в процентах в минуту"
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.locationboss",
                        verbose_name="Босс локации",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трофей с босса",
                "verbose_name_plural": "Трофеи с босса",
            },
        ),
        migrations.CreateModel(
            name="LocationBossCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.locationboss",
                        verbose_name="Босс локации",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж в рейде",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж в рейде",
                "verbose_name_plural": "Персонажи в рейде",
            },
        ),
        migrations.AddField(
            model_name="locationboss",
            name="characters",
            field=models.ManyToManyField(
                through="location.LocationBossCharacter", to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="locationboss",
            name="drop",
            field=models.ManyToManyField(
                related_name="location_boss_drop",
                through="location.LocationBossDrop",
                to="item.item",
            ),
        ),
        migrations.CreateModel(
            name="HuntingZoneDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(
                        default=1, verbose_name="Минимальное количество"
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        default=1, verbose_name="Максимальное количество"
                    ),
                ),
                (
                    "chance",
                    models.FloatField(
                        default=1, verbose_name="Шанс в процентах в минуту"
                    ),
                ),
                (
                    "hunting_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.huntingzone",
                        verbose_name="Зона Охоты",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дроп в зоне охоты",
                "verbose_name_plural": "Дроп в зонах охоты",
            },
        ),
        migrations.AddField(
            model_name="huntingzone",
            name="drop",
            field=models.ManyToManyField(
                related_name="drop", through="location.HuntingZoneDrop", to="item.item"
            ),
        ),
        migrations.AddField(
            model_name="locationboss",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="location.location",
                verbose_name="Локация",
            ),
        ),
        migrations.CreateModel(
            name="DungeonRequiredItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "dungeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.dungeon",
                        verbose_name="Подземелье",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DungeonCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hunting_begin",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 20, 10, 27, 0, 713669, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Начало охоты",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "dungeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.dungeon",
                        verbose_name="Подземелье",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dungeon",
            name="characters",
            field=models.ManyToManyField(
                related_name="dungeon_characters",
                through="location.DungeonCharacter",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="dungeon",
            name="required_items",
            field=models.ManyToManyField(
                related_name="dungeon_required_items",
                through="location.DungeonRequiredItem",
                to="item.item",
            ),
        ),
    ]
