# Generated by Django 4.2.10 on 2024-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselocationmodel",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="location",
            name="exp",
            field=models.IntegerField(
                default=1, verbose_name="Количество опыта в минуту"
            ),
        ),
        migrations.AlterField(
            model_name="locationdrop",
            name="chance",
            field=models.FloatField(
                default=1, verbose_name="Шанс в процентах в минуту"
            ),
        ),
        migrations.AlterField(
            model_name="locationdrop",
            name="max_amount",
            field=models.IntegerField(
                default=1, verbose_name="Максимальное количество"
            ),
        ),
        migrations.AlterField(
            model_name="locationdrop",
            name="min_amount",
            field=models.IntegerField(default=1, verbose_name="Минимальное количество"),
        ),
    ]
