# Generated by Django 4.2.10 on 2024-04-10 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0007_alter_craftingitem_material"),
        ("character", "0014_alter_recipeshare_options"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationBoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="Имя")),
                (
                    "respawn",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Время Респауна"
                    ),
                ),
                (
                    "required_power",
                    models.IntegerField(
                        default=100, verbose_name="Необходимая сила персонажа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Босс Локации",
                "verbose_name_plural": "Боссы Локации",
            },
        ),
        migrations.CreateModel(
            name="LocationBossDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(
                        default=1, verbose_name="Минимальное количество"
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        default=1, verbose_name="Максимальное количество"
                    ),
                ),
                (
                    "chance",
                    models.FloatField(
                        default=1, verbose_name="Шанс в процентах в минуту"
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.locationboss",
                        verbose_name="Босс локации",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трофей с босса",
                "verbose_name_plural": "Трофеи с босса",
            },
        ),
        migrations.CreateModel(
            name="LocationBossCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.locationboss",
                        verbose_name="Босс локации",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж в рейде",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж в рейде",
                "verbose_name_plural": "Персонажи в рейде",
            },
        ),
        migrations.AddField(
            model_name="locationboss",
            name="characters",
            field=models.ManyToManyField(
                through="location.LocationBossCharacter", to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="locationboss",
            name="drop",
            field=models.ManyToManyField(
                related_name="location_boss_drop",
                through="location.LocationBossDrop",
                to="item.item",
            ),
        ),
    ]
