# Generated by Django 4.2.10 on 2024-04-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "location",
            "0002_locationboss_locationbossdrop_locationbosscharacter_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="locationboss",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.location",
                verbose_name="Локация",
            ),
            preserve_default=False,
        ),
    ]
