# Generated by Django 4.2.10 on 2024-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_alter_location_exp_alter_locationdrop_chance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselocationmodel",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Имя"),
        ),
    ]
