# Generated by Django 4.2.10 on 2024-03-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_remove_charactereffect_hunting_minutes_and_more"),
        ("location", "0002_alter_baselocationmodel_name_alter_location_exp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.location",
                        verbose_name="Локация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж в локации",
                "verbose_name_plural": "Персонажи в локациях",
            },
        ),
    ]
