# Generated by Django 4.2.10 on 2024-04-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_locationboss_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="required_power",
            field=models.IntegerField(
                default=100, verbose_name="Требуемая сила персонажа"
            ),
        ),
    ]
