# Generated by Django 4.2.10 on 2024-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0010_remove_charactereffect_hunting_minutes_and_more"),
        ("location", "0003_locationcharacter"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="characters",
            field=models.ManyToManyField(
                through="location.LocationCharacter",
                to="character.character",
                verbose_name="Персонажи в локации",
            ),
        ),
    ]
