# Generated by Django 4.2.10 on 2024-04-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_location_required_power"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="attack",
        ),
        migrations.RemoveField(
            model_name="location",
            name="defence",
        ),
    ]
