# Generated by Django 4.2.10 on 2024-03-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_location_characters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="characters",
        ),
        migrations.DeleteModel(
            name="LocationCharacter",
        ),
    ]
