# Generated by Django 4.2.10 on 2024-04-25 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_alter_dungeoncharacter_hunting_begin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dungeoncharacter",
            name="hunting_begin",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 27, 12, 22, 15, 690635, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Начало охоты",
            ),
        ),
    ]
