# Generated by Django 4.2.10 on 2024-03-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_remove_location_characters_delete_locationcharacter"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="place",
            field=models.IntegerField(default=10, verbose_name="Мест в локации"),
        ),
    ]
