# Generated by Django 4.2.10 on 2024-04-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0012_alter_effect_slug"),
        ("character", "0022_alter_character_health_alter_character_mana_and_more"),
        ("location", "0005_remove_location_attack_remove_location_defence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dungeon",
            fields=[
                (
                    "baselocationmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="location.baselocationmodel",
                    ),
                ),
                (
                    "exp",
                    models.IntegerField(
                        default=1, verbose_name="Количество опыта в минуту"
                    ),
                ),
                (
                    "min_level",
                    models.IntegerField(
                        default=1, verbose_name="Минимальный Уровень Персонажа"
                    ),
                ),
                (
                    "max_level",
                    models.IntegerField(
                        default=1, verbose_name="Минимальный Уровень Персонажа"
                    ),
                ),
                (
                    "cooldown_hours",
                    models.IntegerField(
                        default=24, verbose_name="Ожидание часов для повторного входа"
                    ),
                ),
                (
                    "hunting_hours",
                    models.TimeField(
                        default=4, verbose_name="Часов максимальной охоты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подземелье",
                "verbose_name_plural": "Подземелья",
            },
            bases=("location.baselocationmodel",),
        ),
        migrations.CreateModel(
            name="DungeonRequiredItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "dungeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.dungeon",
                        verbose_name="Подземелье",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DungeonDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(
                        default=1, verbose_name="Минимальное количество"
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        default=1, verbose_name="Максимальное количество"
                    ),
                ),
                (
                    "chance",
                    models.FloatField(
                        default=1, verbose_name="Шанс в процентах в минуту"
                    ),
                ),
                (
                    "dungeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.dungeon",
                        verbose_name="Подземелье",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дроп в локации",
                "verbose_name_plural": "Дроп в локациях",
            },
        ),
        migrations.CreateModel(
            name="DungeonCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hunting_begin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало охоты"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "dungeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.dungeon",
                        verbose_name="Подземелье",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dungeon",
            name="characters",
            field=models.ManyToManyField(
                related_name="в",
                through="location.DungeonCharacter",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="dungeon",
            name="drop",
            field=models.ManyToManyField(
                related_name="dungeon_drop",
                through="location.DungeonDrop",
                to="item.item",
            ),
        ),
        migrations.AddField(
            model_name="dungeon",
            name="required_items",
            field=models.ManyToManyField(
                related_name="dungeon_required_items",
                through="location.DungeonRequiredItem",
                to="item.item",
            ),
        ),
    ]
