# Generated by Django 4.2.10 on 2024-04-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0006_dungeon_dungeonrequireditem_dungeondrop_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dungeon",
            name="hunting_hours",
        ),
    ]
