# Generated by Django 4.2.10 on 2024-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0007_remove_dungeon_hunting_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeon",
            name="hunting_hours",
            field=models.IntegerField(
                default=4, verbose_name="Часов максимальной охоты"
            ),
        ),
    ]
