BUY_BUTTON = "💰Купить"
SELL_BUTTON = "💰Продать"
ITEMS_BUTTON = "🎒Ваши Лоты"
ADD_ON_MARKETPLACE_BUTTON = "💰Выставить на продажу"
ADD_BUTTON = "💰Выставить"
SEARCH_ITEM_BUTTON = "🔎Поиск предмета"
REMOVE_LOT_BUTTON = "❌Снять с продажи"
