version: '3.4'
services:
  postgres-dev-db:
    image: postgres:15
    env_file:
      - ../../.env
    expose:
      - "5432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5432:5432"
    container_name: postgres-dev-game
    volumes:
      - dev-game-data:/var/lib/postgresql/data
    command: -p 5432

volumes:
  dev-game-data:
