# Generated by Django 4.2.10 on 2024-04-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item", "0002_add_etc_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Имя")),
                (
                    "description",
                    models.TextField(max_length=256, verbose_name="Описание"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumLotRequiredItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "premium_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="premium_shop.premiumlot",
                        verbose_name="Премиум Лот",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumLotReceivedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.item",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "premium_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="premium_shop.premiumlot",
                        verbose_name="Премиум Лот",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="premiumlot",
            name="received_items",
            field=models.ManyToManyField(
                related_name="premium_lot_received_items",
                through="premium_shop.PremiumLotReceivedItem",
                to="item.item",
                verbose_name="Получаемые предметы",
            ),
        ),
        migrations.AddField(
            model_name="premiumlot",
            name="required_items",
            field=models.ManyToManyField(
                related_name="premium_lot_required_items",
                through="premium_shop.PremiumLotRequiredItem",
                to="item.item",
                verbose_name="Необходимые предметы",
            ),
        ),
    ]
