EXIT_LOCATION_BUTTON = "👟Выйти из Зоны Охоты"
LOCATIONS_BUTTON = "📍Локации"
DUNGEONS_BUTTON = "☠️Подземелья"
BACKPACK_BUTTON = "🎒Инвентарь"
SKILLS_BUTTON = "✨Способности"
POWER_BUTTON = "⚡️Сила ({})"
ABOUT_BUTTON = "🗣О персонаже"
SHOP_BUTTON = "💰Магазин"

CLASS_CHOOSE_BUTTON = "Выбрать данный класс"
