EQUIP_BUTTON = "⤴️Надеть | ⤵️Снять"
USE_BUTTON = "↗️Использовать"
OPEN_BUTTON = "↗️Открыть"
OPEN_ALL_BUTTON = "↗️Открыть Все!"
USE_MORE_BUTTON = "↗️Использовать Еще!"
OPEN_MORE_BUTTON = "🔃Открыть Еще!"
ENHANCE_BUTTON = "📜Улучшить"
PUT_IN_CLAN_WAREHOUSE_BUTTON = "📩Положить в Клановое Хранилище"
